test: check for workspace variable

diff --git a/.github/workflows/self-hosted.yml b/.github/workflows/self-hosted.yml
--- a/.github/workflows/self-hosted.yml
+++ b/.github/workflows/self-hosted.yml
@@ -1,5 +1,3 @@
-# Original script from https://github.com/ptheywood/cuda-cmake-github-actions
-
 name: Self-Hosted
 
 on:
@@ -26,77 +24,81 @@ jobs:
             gcc: 13
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-
-      - name: Set environment variables
+      - name: Cleanup workspace
         run: |
-          echo "CUDA_PATH=/usr/local/cuda-12.8" >> $GITHUB_ENV
-          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
-          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
-          echo "СС=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
-          echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
-          echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
-          echo "CUDACXX=/usr/local/cuda-${{ matrix.cuda }}/bin/nvcc" >> $GITHUB_ENV
+          echo ${{ github.workspace }}
 
-      - name: Configure CMake build
-        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=ON
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
 
-      - name: Build library sources
-        working-directory: ${{ env.build_dir }}
-        run: cmake --build . --target all --verbose -j `nproc`
+  #     - name: Set environment variables
+  #       run: |
+  #         echo "CUDA_PATH=/usr/local/cuda-12.8" >> $GITHUB_ENV
+  #         echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
+  #         echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+  #         echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
+  #         echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+  #         echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+  #         echo "CUDACXX=/usr/local/cuda-${{ matrix.cuda }}/bin/nvcc" >> $GITHUB_ENV
 
-  test:
-    name: Test ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
-    needs: build
-    runs-on: self-hosted
-    env:
-      unit-test-file: test_fallback.txt
-      regression-test-file: test_regression.txt
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - os: ubuntu-24.04
-            cuda: "12.8"
-            gcc: 13
+  #     - name: Configure CMake build
+  #       run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCUBOOL_BUILD_TESTS=ON
 
-    steps:
-      - name: Run unit-tests
-        working-directory: ${{ env.build_dir }}
-        run: |
-          chmod +x scripts/run_tests_fallback.sh
-          ./scripts/run_tests_fallback.sh | tee ${{ env.unit-test-file }}
+  #     - name: Build library sources
+  #       working-directory: ${{ env.build_dir }}
+  #       run: cmake --build . --target all --verbose -j `nproc`
 
-      - name: Upload unit tests resutls
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.unit-test-file }}
-          path: ${{ env.build_dir }}/${{ env.unit-test-file }}
+  # test:
+  #   name: Test ${{ matrix.os }} GCC ${{ matrix.gcc }} CUDA ${{ matrix.cuda }}
+  #   needs: build
+  #   runs-on: self-hosted
+  #   env:
+  #     unit-test-file: test_fallback.txt
+  #     regression-test-file: test_regression.txt
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - os: ubuntu-24.04
+  #           cuda: "12.8"
+  #           gcc: 13
+
+  #   steps:
+  #     - name: Run unit-tests
+  #       working-directory: ${{ env.build_dir }}
+  #       run: |
+  #         chmod +x scripts/run_tests_fallback.sh
+  #         ./scripts/run_tests_fallback.sh | tee ${{ env.unit-test-file }}
+
+  #     - name: Upload unit tests resutls
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ env.unit-test-file }}
+  #         path: ${{ env.build_dir }}/${{ env.unit-test-file }}
       
-      - name: Check for unit tests results
-        working-directory: ${{ env.build_dir }}
-        run: |
-          if cat ${{ env.unit-test-file }} | grep -q "FAILED"; then
-            exit 1
-          fi
+  #     - name: Check for unit tests results
+  #       working-directory: ${{ env.build_dir }}
+  #       run: |
+  #         if cat ${{ env.unit-test-file }} | grep -q "FAILED"; then
+  #           exit 1
+  #         fi
 
-      - name: Run regression-tests
-        working-directory: ${{ env.build_dir }}/python
-        run: |
-          chmod +x run_tests.sh
-          ./run_tests.sh | tee ${{ env.regression-test-file }}
+  #     - name: Run regression-tests
+  #       working-directory: ${{ env.build_dir }}/python
+  #       run: |
+  #         chmod +x run_tests.sh
+  #         ./run_tests.sh | tee ${{ env.regression-test-file }}
 
-      - name: Upload regression tests resutls
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.regression-test-file }}
-          path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}
+  #     - name: Upload regression tests resutls
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: ${{ env.regression-test-file }}
+  #         path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}
 
-      - name: Check for regression tests results
-        working-directory: ${{ env.build_dir }}/python
-        run: |
-          if cat ${{ env.regression-test-file }} | grep -q "FAILED"; then
-            exit 1
-          fi
+  #     - name: Check for regression tests results
+  #       working-directory: ${{ env.build_dir }}/python
+  #       run: |
+  #         if cat ${{ env.regression-test-file }} | grep -q "FAILED"; then
+  #           exit 1
+  #         fi
