test: cleanup in failed pipeline

diff --git a/.github/workflows/self-hosted.yml b/.github/workflows/self-hosted.yml
--- a/.github/workflows/self-hosted.yml
+++ b/.github/workflows/self-hosted.yml
@@ -50,8 +50,8 @@ jobs:
     needs: build
     runs-on: self-hosted
     env:
-      unit-test-file: test_all.txt
-      regression-test-file: test_regression.txt
+      unit-test-file: test_all.log
+      regression-test-file: test_regression.log
     strategy:
       fail-fast: false
       matrix:
@@ -59,41 +59,44 @@ jobs:
           - gpu: NVIDIA-GeForce-GT-1030
 
     steps:
-      - name: Run unit-tests
-        working-directory: ${{ env.build_dir }}
+      - name: Fail
         run: |
-          source scripts/run_tests_all.sh | tee ${{ env.unit-test-file }}
+          exit 1
+      # - name: Run unit-tests
+      #   working-directory: ${{ env.build_dir }}
+      #   run: |
+      #     source scripts/run_tests_all.sh | tee ${{ env.unit-test-file }}
 
-      - name: Upload unit tests resutls
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.unit-test-file }}
-          path: ${{ env.build_dir }}/${{ env.unit-test-file }}
+      # - name: Upload unit tests resutls
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.unit-test-file }}
+      #     path: ${{ env.build_dir }}/${{ env.unit-test-file }}
 
-      - name: Check for unit tests results
-        working-directory: ${{ env.build_dir }}
-        run: |
-          if grep -q "FAILED" ${{ env.unit-test-file }}; then
-            exit 1
-          fi
+      # - name: Check for unit tests results
+      #   working-directory: ${{ env.build_dir }}
+      #   run: |
+      #     if grep -q "FAILED" ${{ env.unit-test-file }}; then
+      #       exit 1
+      #     fi
 
-      - name: Run regression-tests
-        working-directory: ${{ env.build_dir }}/python
-        run: |
-          source run_tests.sh | tee ${{ env.regression-test-file }}
+      # - name: Run regression-tests
+      #   working-directory: ${{ env.build_dir }}/python
+      #   run: |
+      #     source run_tests.sh 2>&1 | tee ${{ env.regression-test-file }}
 
-      - name: Upload regression tests resutls
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ env.regression-test-file }}
-          path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}
+      # - name: Upload regression tests resutls
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: ${{ env.regression-test-file }}
+      #     path: ${{ env.build_dir }}/python/${{ env.regression-test-file }}
 
-      - name: Check for regression tests results
-        working-directory: ${{ env.build_dir }}/python
-        run: |
-          if grep -q "FAILED" ${{ env.regression-test-file }}; then
-            exit 1
-          fi
+      # - name: Check for regression tests results
+      #   working-directory: ${{ env.build_dir }}/python
+      #   run: |
+      #     if grep -q "FAILED" ${{ env.regression-test-file }}; then
+      #       exit 1
+      #     fi
   
   clean:
     name: Cleanup workspace
